all: 
  db: &db_defaults 
    host: localhost
    port: 27017
    name: dharma_api

test:
  db:
    <<: *db_defaults
    name: test

development:
  db:
    <<: *db_defaults 

production:
  db:
    name: heroku_app4680507
    port: 33477
    host: ds033477.mongolab.com
    user: heroku_app4680507
    password: <%= ['MONGOLAB_PASSWORD'] %>